### ISSUE TITLE
Issue with seam allowances

### ISSUE THREAD

**Issue by dmenchaca** [abroekhof/waldbasketbag#4]
Hi @abroekhof,

Thanks for creating this pattern.

I see on the instructions you mention:

> Seam allowances are 3/8”

Yet on the pdf for the sides and bottom I see a seam allowance of 3/4 inch and for the collar 3/8 inch. 

Which seam allowance is right? My guess is that I may not be reading the pdf right.

Thanks!

**Comment by abroekhof** [comment]
Hey Diego,
You are indeed reading the PDF wrong! :smile: (but I also didn't make it super clear). The 3/4" you're seeing is the full width of the panel, which includes two 3/8" allowances for the total of 3/4".

Let me know if that makes sense!

-Alex

**Comment by dmenchaca** [comment]
@abroekhof thanks for the fast answer.

I thought I wasn't reading it right 😅

Please mind my ignorance, this is my first sewing project. How come then the sides and bottom have double allowance?

Thanks Alex!

**Comment by abroekhof** [comment]
No worries, stoked you're using the pattern. 

What do you mean by double allowance? So for example, the side panel is 5 inches tall, or it will be once it's sewn into the bag. On both sides of that panel, there are 3/8" seam allowances that will be hidden once the bag is done. 
![image](https://github.com/abroekhof/waldbasketbag/assets/3480381/52199acc-5dae-42af-9269-364cfcadbe7a)
So the full height of the panel is 5+3/8+3/8 = 5 3/4".

The collar only has a seam allowance on one side because only one edge is sewn. The other edge is rolled and attached to the webbing.

**Comment by dmenchaca** [comment]
I just realised how silly my question was 😂.  I totally got it now.

Thanks a ton! I'll share a pictures here once I'm done.

**Comment by abroekhof** [comment]
No worries! It also took me a while to get a hang of all these extra measurements, it's a lot to keep track of.

Good luck, looking forward to the pics!

**Comment by dmenchaca** [comment]
@abroekhof for higher weatherproofness I'm debating whether to bind the seams with grosgrain ribbon or a PU seam sealing tape.

Have you ever noticed water making it's way through the seams?

**Comment by abroekhof** [comment]
I'm in Bay Area, and don't ride in the rain extensively, but the times I have, I have not noticed much leakage through grosgrain bound seams.

**Comment by dmenchaca** [comment]
Gotcha, thanks!
